services:
  # Backend API Service
  - type: web
    name: datacrm-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        value: file:./prisma/dev.db
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: datacrm-frontend
          property: host

  # Frontend Next.js Service  
  - type: web
    name: datacrm-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: datacrm-frontend
          property: host
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: datacrm-backend
          property: host
